import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire('C:/Users/Acer/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json');
const {chromium}=require('playwright');
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:process.argv.includes('--unsafe-file')?['--allow-file-access-from-files','--disable-web-security']:process.argv.includes('--allow-file')?['--allow-file-access-from-files']:[]});
const page=await browser.newPage({viewport:{width:1365,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const consoleErrors=[];page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
await page.goto(process.argv[2]||'http://127.0.0.1:8765');
const files=fs.readdirSync('..').filter(n=>n.endsWith('.pdf')).map(n=>path.resolve('..',n));
await page.locator('#files').setInputFiles(files);
await page.waitForFunction(()=>document.getElementById('count').textContent==='2'&&!document.body.classList.contains('busy')).catch(async error=>{console.log(JSON.stringify({messages:await page.locator('#messages').innerText(),errors,consoleErrors}));throw error;});
assert.equal(await page.locator('#total').textContent(),'฿60,000.00');
assert.equal(await page.locator('#campaignTotal').textContent(),'฿60,000.00');
assert.equal(await page.locator('#claimRows tr').count(),2);
assert.equal(await page.locator('#claimTotal').textContent(),'60,000.00');
assert.match(await page.locator('#claimRows').textContent(),/GBCFB526F4/);
assert.match(await page.locator('#claimRows').textContent(),/FBADS-336-106434674/);
await page.locator('#owner').fill('คุณดิเรก คำไพบูลย์');
assert.match(await page.locator('#claimRows').textContent(),/คุณดิเรก คำไพบูลย์/);
assert.equal(await page.locator('#campaigns tr').count(),19);
assert.equal(await page.locator('.area').count(),11);
await page.screenshot({path:'desktop-check.png',fullPage:true});
await page.locator('#files').setInputFiles(files[0]);
await page.waitForFunction(()=>!document.body.classList.contains('busy'));
assert.equal(await page.locator('#total').textContent(),'฿60,000.00');
assert.match(await page.locator('#messages').textContent(),/ซ้ำ/);
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
await page.screenshot({path:'mobile-check.png',fullPage:true});
await page.locator('.remove').first().click();
assert.equal(await page.locator('#total').textContent(),'฿30,000.00');
await page.locator('.remove').first().click();
assert.equal(await page.locator('#total').textContent(),'฿0.00');
assert.equal(await page.locator('#count').textContent(),'0');
// Validate WebMCP registration and both input paths in an isolated supported registry shim.
await page.addInitScript(()=>{document.modelContext={registerTool(tool){window.summaryTool=tool;}};});
await page.reload();await page.waitForFunction(()=>!!window.summaryTool);
const tool=await page.evaluate(async()=>({name:window.summaryTool.name,schema:window.summaryTool.inputSchema,annotations:window.summaryTool.annotations,result:await window.summaryTool.execute({}),invalid:(()=>{try{window.summaryTool.execute({unexpected:true});return false;}catch{return true;}})()}));
assert.equal(tool.name,'read_receipt_summary');assert.equal(tool.result.total,0);assert.equal(tool.invalid,true);
await page.locator('#files').setInputFiles(files);
await page.waitForFunction(()=>!document.body.classList.contains('busy')&&document.getElementById('count').textContent==='2');
assert.equal(await page.evaluate(()=>window.summaryTool.execute({}).total),6000000);
assert.deepEqual(errors,[]);
console.log(JSON.stringify({import:true,duplicate:true,delete:true,mobileOverflow:false,webmcpShim:true,errors}));
await browser.close();
